### ISSUE TITLE
Page list

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-celebrations/celebrate-drupal-9#2]
Below is a list of possible content pages that we'll need for the website:

### Base
- [x] Homepage (call to action, view of recent videos/photos) #8 
- [x] User registration #9 
- [x] Contact #10 

### Video
- [ ] How to add a Video/submit #4 
- [x] View all Videos #6 

### Photo
- [ ] How to add a Photo/submit #5 
- [x] View all Photos

### About
- [x] About the project and About the team, Inspired by Celebr8

### Remote (this all should go on one page)
- [ ] Release parties (perhaps 2 main key ones, then allow users to add their own)
- [ ] Remote rooms for sessions to be live-streamed
- [ ] Chat (link to Drupal Chat / Drupal Slack)

Feel free to add your ideas and we can update this list.

We can create separate issues for each page, and break down those issues into smaller manageable chunks that can be worked.

**Comment by dan2k3k4** [comment]
Designs can be found at: https://www.figma.com/file/UbJpt1RvUHmkrPENnHMqqF

**Comment by zsofimajor** [comment]
I added some comments, merges pages too. I don't think we want to have too many pages, the 'how to' and submit can easily go on the same.
