### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by dan2k3k4** [drupal-celebrations/celebrate-drupal-9#8]
- [x] Homepage content is finalised
- [x] Homepage hero is styled #21 
- [x] Homepage content is styled #22 
- [x] Anonymous users see login button #23
- [x] Homepage contains latest photos/videos and on click leads to respective pages #24

**Comment by goba** [comment]
Would love to help with this. How can I do that?

**Comment by dan2k3k4** [comment]
@goba great, I've sent you a login for prod to help with content.

I think I may need to disable the `* > * { border: 1px dashed gray; }` styling or make it turn on just for me locally.

Homepage should help to explain the project and the features (add videos for the celebration, add images for the celebrations: baked recipes? drawings? selfies?).

I believe we'd need to add the taxonomy terms as I only added 2-3 for the categories.

**Comment by miromichalicka** [comment]
Thsi issue shoudl be broken down to multiple subissues.

**Comment by zsofimajor** [comment]
sub issues are created.
